import React,{useState} from 'react';
import {BrowserRouter,Routes,Route,NavLink,Link,useLocation} from 'react-router-dom';
import {Helmet,HelmetProvider} from 'react-helmet-async';
import {FiArrowRight,FiCheck,FiChevronDown,FiMail,FiMapPin,FiPhone,FiSearch,FiMenu,FiX,FiDownload} from 'react-icons/fi';
import {products,services,industries} from './data';
import './index.css';
import img1 from "./Assets/modern-bathroom-system.jpeg"
// import img2 from "./Assets/bathroom-01.jpeg"

const seo={
 '/':['CN2 International LLC | Sanitary Ware Supplier','International sanitary ware supplier sourcing from China and Europe for European markets. Explore products, services and project supply solutions.'],
 '/about':['About CN2 International | International Sanitary Ware Supplier','Learn about CN2 International LLC and its international sanitary ware supply approach.'],
 '/products':['Sanitary Ware Products | CN2 International','Explore toilets, wash basins, sinks, bathtubs, showers, faucets, bidets and bathroom accessories.'],
 '/services':['Sanitary Ware Supply Services | CN2 International','International sourcing, bulk orders, OEM support and project supply services.'],
 '/industries':['Industries We Serve | CN2 International','Sanitary ware supply solutions for construction, hospitality, real estate, retail and other industries.'],
 '/contact':['Contact CN2 International | Request a Quote','Contact CN2 International LLC for sanitary ware product enquiries and quotation requests.'],
 '/privacy':['Privacy Policy | CN2 International','Privacy policy for CN2 International LLC.'],
 '/terms':['Terms & Conditions | CN2 International','Terms and conditions for CN2 International LLC.']
};


function Seo(){const p=seo[window.location.pathname]||seo['/'];return <Helmet><title>{p[0]}</title><meta name="description" content={p[1]}/><link rel="canonical" href={'https://cn2international.com'+window.location.pathname}/><meta property="og:title" content={p[0]}/><meta property="og:description" content={p[1]}/><meta property="og:type" content="website"/><meta property="og:url" content={'https://cn2international.com'+window.location.pathname}/></Helmet>}

function Header(){const [open,setOpen]=useState(false);const nav=[['/','Home'],['/about','About Us'],['/products','Products'],['/services','Services'],['/industries','Industries'],['/contact','Contact Us']];return <header className="header"><div className="container nav"><Link to="/" className="brand"><img src="/logo.svg"/><span>CN2 <b>INTERNATIONAL</b></span></Link><button className="menu" onClick={()=>setOpen(!open)}>{open?<FiX/>:<FiMenu/>}</button><nav className={open?'open':''}>{nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}>{label}</NavLink>)}<Link className="nav-cta" to="/contact" onClick={()=>setOpen(false)}>Request a Quote <FiArrowRight/></Link></nav></div></header>}


function Footer(){return <footer><div className="container footer-grid"><div><img className="footer-logo" src="/logo.svg"/><p>International sanitary ware supply for residential, commercial and project requirements across European markets.</p></div><div><h4>Company</h4><Link to="/about">About Us</Link><Link to="/products">Products</Link><Link to="/services">Services</Link><Link to="/industries">Industries</Link></div><div><h4>Contact</h4><span><FiMapPin/>222 Broadway, New York, NY 10038</span><span><FiPhone/>+8674840894</span><span><FiMail/>cn2internationalllc@gmail.com</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} CN2 International LLC. All rights reserved.</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div></footer>}


function Layout({children}){return <><Seo/><Header/><main>{children}</main><Footer/></>}


function Hero(){
    return <section className="hero">
        <div className="container hero-grid">
            <div>
                <div className="eyebrow">INTERNATIONAL SANITARY WARE SUPPLY</div>
                <h1>CN2<br/><em>INTERNATIONAL LLC.</em></h1>
                <p>CN2 International connects quality sanitary ware sourcing across China and Europe with customers and projects serving European markets.</p><div className="actions"><Link className="btn primary" to="/products">Explore Products <FiArrowRight/></Link><Link className="btn secondary" to="/contact">Request a Quote</Link></div><div className="trust"><span><FiCheck/>China & Europe sourcing</span><span><FiCheck/>European market focus</span><span><FiCheck/>Custom & OEM support</span></div></div><div className="hero-visual"><div className="visual-top"><span>CN2 / SUPPLY</span><span>01</span></div><img className="hero-image" src={img1} alt="Modern bathroom sanitary ware system" />
                <div className="visual-overlay"></div><div className="visual-bottom"><b>MODERN BATHROOM SYSTEMS</b><span>Specification-led supply</span></div></div></div></section>}



function SectionTitle({kicker,title,text}){return <div className="section-title"><div className="eyebrow">{kicker}</div><h2>{title}</h2>{text&&<p>{text}</p>}</div>}

function Home(){return <><Hero/><section className="section light"><div className="container"><SectionTitle kicker="PRODUCT RANGE" title="Essential sanitary ware for modern spaces" text="A focused product range covering the most widely specified bathroom categories."/><div className="product-grid">{products.slice(0,6).map(p=><ProductCard key={p.name} p={p}/>)}</div><div className="center"><Link className="text-link" to="/products">View all products <FiArrowRight/></Link></div></div></section><section className="section"><div className="container split"><div className="blue-panel"><span className="eyebrow">WHY CN2</span><h2>One supplier for a complex international supply chain.</h2><p>CN2 International supports sourcing and supply requirements with a practical approach to products, specifications and project needs.</p><Link className="btn white" to="/about">About CN2 <FiArrowRight/></Link></div><div className="feature-list">{['International supplier positioning','China and Europe sourcing network','Custom and OEM enquiry support','Project and bulk-order coordination'].map(x=><div className="feature" key={x}><span><FiCheck/></span><div><h3>{x}</h3><p>Structured around clear specifications and customer requirements.</p></div></div>)}</div></div></section><section className="section light"><div className="container"><SectionTitle kicker="SERVICES" title="Supply support built around your requirements"/><div className="service-grid">{services.slice(0,4).map(([a,b])=><div className="service" key={a}><span className="num">0{services.findIndex(s=>s[0]===a)+1}</span><h3>{a}</h3><p>{b}</p><Link to="/services">Learn more <FiArrowRight/></Link></div>)}</div></div></section><CTA/></>}
function ProductCard({p}){const [zoom,setZoom]=useState(false);return <><article className="product-card"><div className={`product-art ${p.image?'has-image':'image-slot'}`}><Link to={'/contact?product='+encodeURIComponent(p.name)} aria-label={'Enquire about '+p.name}><img src={p.image} alt={p.image ? p.name : `Add image for ${p.name}`} style={{objectFit:p.objectFit||'cover'}} /></Link>{p.image&&<button className="image-zoom" type="button" onClick={()=>setZoom(true)} aria-label={`Enlarge ${p.name} image`}><FiSearch/></button>}</div><div><div className="tag">SANITARY WARE</div><h3>{p.name}</h3><p>{p.desc}</p><Link to={'/contact?product='+encodeURIComponent(p.name)}>Enquire <FiArrowRight/></Link></div></article>{zoom&&<div className="image-lightbox" role="dialog" aria-modal="true" aria-label={`${p.name} image preview`} onClick={()=>setZoom(false)}><button className="lightbox-close" type="button" onClick={()=>setZoom(false)} aria-label="Close image preview"><FiX/></button><img src={p.image} alt={p.name} onClick={e=>e.stopPropagation()}/></div>}</>}
function Products(){const [q,setQ]=useState('');const list=products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));return <div><PageHero kicker="PRODUCTS" title="Sanitary ware for modern specifications" text="Explore CN2 International's core sanitary ware categories and enquire about product availability, specifications and bulk requirements."/><section className="section light"><div className="container"><div className="search"><FiSearch/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/></div><div className="product-grid full">{list.map(p=><ProductCard key={p.name} p={p}/>)}</div>{!list.length&&<div className="empty">No product category matched your search.</div>}</div></section><CTA/></div>}
function PageHero({kicker,title,text}){return <section className="page-hero"><div className="container"><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{text}</p></div></section>}


function About(){return <><PageHero kicker="ABOUT CN2" title="An international supplier focused on sanitary ware." text="CN2 International LLC supplies sanitary ware for customers, distributors and projects serving European markets, with sourcing across China and Europe."/><section className="section"><div className="container split about"><div><SectionTitle kicker="OUR APPROACH" title="Practical supply, clear specifications." text="We focus on helping customers identify suitable sanitary ware products and coordinate sourcing around their requirements."/></div><div className="copy"><p>CN2 International operates as an international sanitary ware supplier. Our product focus includes toilets, wash basins, sinks, bathtubs, showers, faucets, bidets and bathroom accessories.</p><p>For custom requirements, CN2 can support OEM enquiries and sourcing conversations. Product availability, specifications, commercial terms and delivery arrangements are confirmed individually for each enquiry.</p></div></div></section><section className="section light"><div className="container"><SectionTitle kicker="MISSION & VISION" title="Built around dependable international supply."/><div className="mv-grid"><div><h3>Mission</h3><p>To make sanitary ware sourcing more straightforward by connecting customers with suitable products and supply options across China and Europe.</p></div><div><h3>Vision</h3><p>To build a trusted international supply platform for modern sanitary ware and bathroom solutions.</p></div></div></div></section><CTA/></>}
function Services(){return <><PageHero kicker="SERVICES" title="Professional supply services for sanitary ware." text="From product sourcing to bulk and project enquiries, CN2 International structures its support around customer requirements."/><section className="section light"><div className="container service-grid six">{services.map(([a,b],i)=><div className="service" key={a}><span className="num">{String(i+1).padStart(2,'0')}</span><h3>{a}</h3><p>{b}</p><Link to="/contact">Discuss your requirement <FiArrowRight/></Link></div>)}</div></section><CTA/></>}
function Industries(){return <><PageHero kicker="INDUSTRIES" title="Sanitary ware supply across multiple project environments." text="Our range and sourcing approach can support a broad set of construction, property, hospitality and distribution requirements."/><section className="section"><div className="container industry-grid">{industries.map((x,i)=><div className="industry" key={x}><span>0{i+1}</span><h3>{x}</h3><p>Sanitary ware sourcing and supply support aligned to project or commercial requirements.</p></div>)}</div></section><CTA/></>}
function Contact(){const [sent,setSent]=useState(false);return <><PageHero kicker="CONTACT US" title="Let's discuss your sanitary ware requirement." text="Send us your details and requirement. Our team can follow up with product information, sourcing options and quotation discussions."/><section className="section light"><div className="container contact-grid"><div><SectionTitle kicker="CN2 INTERNATIONAL LLC" title="Request a quote or product enquiry" text="Tell us what you need and we'll use your enquiry to understand the next step."/><div className="contact-detail"><FiMapPin/><div><b>Address</b><span>222 Broadway, New York, NY 10038, USA</span></div></div><div className="contact-detail"><FiPhone/><div><b>Phone</b><span>+8674840894</span></div></div><div className="contact-detail"><FiMail/><div><b>Sales</b><span>Cn2international.sales@gmail.com</span></div></div></div><form className="form" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent&&<div className="success">Thank you. Your enquiry has been captured in this demo form. Connect the form to your preferred email/backend before launch.</div>}<label>Name<input required name="name"/></label><label>Email<input required type="email" name="email"/></label><label>Phone<input name="phone"/></label><label>Message<textarea required name="message" rows="7" placeholder="Tell us about the products, quantity or project..."/></label><button className="btn primary" type="submit">Send Enquiry <FiArrowRight/></button></form></div></section></>}
function CTA(){return <section className="cta"><div className="container cta-inner"><div><div className="eyebrow">START A CONVERSATION</div><h2>Need sanitary ware for a project?</h2><p>Share your requirements and discuss sourcing, product options or a quotation.</p></div><Link className="btn white" to="/contact">Request a Quote <FiArrowRight/></Link></div></section>}
function Legal({terms=false}){return <section className="section legal"><div className="container"><SectionTitle kicker={terms?'TERMS & CONDITIONS':'PRIVACY POLICY'} title={terms?'Terms & Conditions':'Privacy Policy'}/><p>CN2 International LLC provides this page as general website information. Specific commercial terms, product specifications, delivery arrangements, warranties and other conditions are confirmed in applicable quotations, purchase orders or agreements.</p><h3>Website information</h3><p>We aim to keep website information useful and current, but product availability, specifications and pricing may change. Visitors should confirm details with CN2 International before relying on them for a purchase or project.</p><h3>Contact information</h3><p>For enquiries, contact CN2 International LLC at 222 Broadway, New York, NY 10038, USA, +8674840894, or cn2internationalllc@gmail.com.</p><h3>Enquiry data</h3><p>Information submitted through contact forms may be used to respond to your enquiry and manage communications relating to your request. Do not submit confidential information through the website form.</p></div></section>}


function Catalogue(){const rows=products.map(p=>`<tr><td>${p.name}</td><td>${p.desc}</td></tr>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><title>CN2 International Product Catalogue</title><style>body{font-family:Arial;color:#10283f;margin:50px}h1{font-size:34px}p,td{color:#637486;line-height:1.6}table{width:100%;border-collapse:collapse;margin-top:30px}td{padding:14px;border:1px solid #dce5ea}td:first-child{color:#10283f;font-weight:bold;width:30%}</style></head><body><h1>CN2 INTERNATIONAL</h1><p>SANITARY WARE PRODUCT CATALOGUE</p><p>International sanitary ware supply for European markets. Sourcing across China and Europe.</p><table>${rows}</table><p style="margin-top:35px">222 Broadway, New York, NY 10038, USA · +8674840894 · Cn2international.sales@gmail.com</p></body></html>`;return <PageHero kicker="PRODUCT CATALOGUE" title="Download our product category catalogue" text="A concise overview of CN2 International's core sanitary ware categories."/>}
function App(){return <BrowserRouter><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/products" element={<Products/>}/><Route path="/services" element={<Services/>}/><Route path="/industries" element={<Industries/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy" element={<Legal/>}/><Route path="/terms" element={<Legal terms/>}/><Route path="*" element={<Home/>}/></Routes></Layout></BrowserRouter>}
export default function Root(){return <HelmetProvider><App/></HelmetProvider>}
